In [1]:
import os

import gempy as gp
import numpy as np
import pandas as pd

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

The data used for the construction of a model in GemPy is stored in Python objects. The main data classes are:

    -  Surface_points
    -  Orientations
    -  Grid
    -  Surfaces
    -  Series
    -  Additional data
    -  Faults

# Workflow
1. Series
2. Faults
3. Surfaces
4. Map series to surfaces
5. Data

In [2]:
geo_model = gp.create_model('GeoModel')

### 1. Series object
- Properties associated with each independent scalar field.
- Order of series, ...
- Index of series are pandas categories.

In [3]:
geo_model.series

                order_series BottomRelation
Default series             1        Erosion

In [4]:
# modifiy series
geo_model.series.set_series_index(['serie_1', 'serie_2', 'serie_3'])

         order_series BottomRelation
serie_1             1        Erosion
serie_2             2        Erosion
serie_3             3        Erosion

In [5]:
# adding a new serie
geo_model.series.add_series('serie_4')
geo_model.series.add_series('serie_44')

          order_series BottomRelation
serie_1              1        Erosion
serie_2              2        Erosion
serie_3              3        Erosion
serie_4              4        Erosion
serie_44             5        Erosion

In [6]:
# delete and rename
geo_model.series.delete_series('serie_4')
geo_model.series.delete_series('serie_3')
geo_model.series.rename_series({'serie_44':'serie_3'})

         order_series BottomRelation
serie_1             1        Erosion
serie_2             2        Erosion
serie_3             3        Erosion

In [8]:
# reorder
geo_model.series.reorder_series(['serie_3', 'serie_2', 'serie_1'])

         order_series BottomRelation
serie_3             1        Erosion
serie_2             2        Erosion
serie_1             3        Erosion

### 2. Faults
- charectirize which mathematical series behave as fault

In [9]:
# set fault
geo_model.faults.set_is_fault(['serie_3'])

         isFault  isFinite
serie_3     True     False
serie_2    False     False
serie_1    False     False

In [10]:
geo_model.faults.faults_relations_df

         serie_3  serie_2  serie_1
serie_3    False     True     True
serie_2    False    False    False
serie_1    False    False    False

### 3. Surfaces

In [11]:
geo_model.surfaces

Empty DataFrame
Columns: [surface, series, order_surfaces, isBasement, color, vertices, edges, id]
Index: []

In [12]:
# We can set any number of formations by passing a list with the names. 
# By default they will take the name or the first series.
geo_model.surfaces.set_surfaces_names([
        'surface_1',
        'surface_2',
        'surface_3',
        'surface_4',
        'surface_5',
        'surface_6',
        'surface_7',
        'surface_8'
])

     surface   series  order_surfaces  isBasement    color vertices edges  id
0  surface_1  serie_1               1       False  #015482      NaN   NaN   1
1  surface_2  serie_1               2       False  #9f0052      NaN   NaN   2
2  surface_3  serie_1               3       False  #ffbe00      NaN   NaN   3
3  surface_4  serie_1               4       False  #728f02      NaN   NaN   4
4  surface_5  serie_1               5       False  #443988      NaN   NaN   5
5  surface_6  serie_1               6       False  #ff3f20      NaN   NaN   6
6  surface_7  serie_1               7       False  #325916      NaN   NaN   7
7  surface_8  serie_1               8        True  #5DA629      NaN   NaN   8

In [13]:
geo_model.surfaces.add_surface(['surface_9'])

     surface   series  order_surfaces  isBasement    color vertices edges  id
0  surface_1  serie_1               1       False  #015482      NaN   NaN   1
1  surface_2  serie_1               2       False  #9f0052      NaN   NaN   2
2  surface_3  serie_1               3       False  #ffbe00      NaN   NaN   3
3  surface_4  serie_1               4       False  #728f02      NaN   NaN   4
4  surface_5  serie_1               5       False  #443988      NaN   NaN   5
5  surface_6  serie_1               6       False  #ff3f20      NaN   NaN   6
6  surface_7  serie_1               7       False  #325916      NaN   NaN   7
7  surface_8  serie_1               8       False  #5DA629      NaN   NaN   8
8  surface_9  serie_1               9        True  #acc2d9      NaN   NaN   9

In [14]:
geo_model.surfaces.set_surfaces_values([2,2,2,5,5,6,6,7,7])

     surface   series  order_surfaces  isBasement    color  id  value_0
0  surface_1  serie_1               1       False  #015482   1        2
1  surface_2  serie_1               2       False  #9f0052   2        2
2  surface_3  serie_1               3       False  #ffbe00   3        2
3  surface_4  serie_1               4       False  #728f02   4        5
4  surface_5  serie_1               5       False  #443988   5        5
5  surface_6  serie_1               6       False  #ff3f20   6        6
6  surface_7  serie_1               7       False  #325916   7        6
7  surface_8  serie_1               8       False  #5DA629   8        7
8  surface_9  serie_1               9        True  #acc2d9   9        7

In [15]:
geo_model.surfaces.add_surfaces_values(
    [[1,1,1,1,1,2,2,2,2]],
    ['val_1']
)

     surface   series  order_surfaces  isBasement    color  id  value_0  val_1
0  surface_1  serie_1               1       False  #015482   1        2      1
1  surface_2  serie_1               2       False  #9f0052   2        2      1
2  surface_3  serie_1               3       False  #ffbe00   3        2      1
3  surface_4  serie_1               4       False  #728f02   4        5      1
4  surface_5  serie_1               5       False  #443988   5        5      1
5  surface_6  serie_1               6       False  #ff3f20   6        6      2
6  surface_7  serie_1               7       False  #325916   7        6      2
7  surface_8  serie_1               8       False  #5DA629   8        7      2
8  surface_9  serie_1               9        True  #acc2d9   9        7      2

### 4. Map series to formation

In [16]:
gp.map_series_to_surfaces(
    geo_model,
    {
        'serie_1': (
            'surface_1',
            'surface_2',
            'surface_3',
            'surface_4',
            'surface_5'
        ),
        'serie_2': ('surface_6'),
        'serie_3': (
            'surface_7',
            'surface_8',
            'surface_9'
        )
    }
)

     surface   series  order_surfaces  isBasement    color  id  value_0  val_1
6  surface_7  serie_3               1       False  #325916   1        6      2
7  surface_8  serie_3               2       False  #5DA629   2        7      2
8  surface_9  serie_3               3       False  #acc2d9   3        7      2
5  surface_6  serie_2               1       False  #ff3f20   4        6      2
0  surface_1  serie_1               1       False  #015482   5        2      1
1  surface_2  serie_1               2       False  #9f0052   6        2      1
2  surface_3  serie_1               3       False  #ffbe00   7        2      1
3  surface_4  serie_1               4       False  #728f02   8        5      1
4  surface_5  serie_1               5        True  #443988   9        5      1

### Data

In [18]:
geo_model.surface_points

Empty DataFrame
Columns: [X, Y, Z, X_r, Y_r, Z_r, surface, series, id, order_series, smooth]
Index: []

In [20]:
geo_model.orientations

Empty DataFrame
Columns: [X, Y, Z, X_r, Y_r, Z_r, G_x, G_y, G_z, dip, azimuth, polarity, surface, series, id, order_series, smooth]
Index: []